Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2],[3,4]])

In [4]:
arr2 = np.array([[1,2],[3,4]])

In [5]:
mul = arr1 * arr2
mul

array([[ 1,  4],
       [ 9, 16]])

In [8]:
sum = arr1 + arr2
sum

array([[2, 4],
       [6, 8]])

In [9]:
subtract = arr1 - arr2
subtract

array([[0, 0],
       [0, 0]])

In [10]:
div = arr1/arr2
div

array([[1., 1.],
       [1., 1.]])